### ISSUE TITLE
[Request] Some very brief documentation on parameters

### ISSUE THREAD

**Issue by jolespin** [matteodellamico/flexible-clustering#5]
It's quite a lot of work to add verbose documentation and especially creating a website for it.   That's quite a big ask to develop an entire documentation set so Instead of doing that, would it be possible for you to just describe the parameters here? 

The parameters for `FISHDBC` class initialization:
```
flexible_clustering.FISHDBC(
    d,
    min_samples=5,
    m=5,
    ef=50,
    m0=None,
    level_mult=None,
    heuristic=True,
    balanced_add=True,
    vectorized=False,
)
```

The parameters for the `.cluster` method:
```
clusterer.cluster(
    min_cluster_size=None,
    cluster_selection_method='eom',
    allow_single_cluster=False,
    match_reference_implementation=False,
)
```

Lastly, the output values from `.cluster`:

```
labels, probs, stabilities, condensed_tree, slt, mst = clusterer.cluster()
```

I plan to use this on a fairly large dataset and integrate it in a few pipelines so I want to make sure I'm using it correctly.

**Comment by matteodellamico** [comment]
* `d` is the distance function
 * `min_samples`, the `.cluster()` method parameters and return values of  come from the HDBSCAN parameters, look them up here: https://hdbscan.readthedocs.io/en/latest/
 * the others are HNSW parameters; you can find them explained in https://arxiv.org/abs/1603.09320 but the defaults are likely to be fine and the one you're most likely to play with is going to be ef--lower values will result in a faster approach with lower accuracy
 * the one exception is balanced_add, which changes the implementation of the HNSW add method from what is described in the paper. Set it to False to mimic the paper's version. As far as I have seen, it changes little.

**Comment by jolespin** [comment]
Excellent!  I appreciate the explanation.  Looking forward to diving deeper into this tool and the usage. 

Have you had scenarios where the majority of the observations/samples are in the outlier cluster? What are the methods you use to relax the cluster inclusion a bit?

**Comment by matteodellamico** [comment]
The most likely choice would probably be to lower `min_samples` and `min_cluster_size` (if set), but check the HDBSCAN documentation for that.

I am curious: what are you looking at FISHDBC for?

**Comment by jolespin** [comment]
I'm using it for clustering thousands of genomes.  Loving the versatility and speed of FISHDBC with the custom distances. 

Is there a way to build a FISHDBC model from a precomputed distance matrix? For example, the following workflow would be ideal if you're going to be adding future updates: 


```python
pairwise_distances = # Output of scipy's pdist 

params = dict(
    d = #distance function used,
    min_samples=5,
    ...
)

clusterer = FISHDBC.from_precomputed_distances(pairwise_distances= pairwise_distances, **params)

# New data
for elem in some_new_data: # support cheap incremental clustering
    clusterer.add(elem)
```

**Comment by matteodellamico** [comment]
Amazing! I've been looking for use cases like that for a long time. Would you mind having a call about that? You can contact me at matteodellamico-at-gmail.com.

Now, with respect to your question: you may just define a distance function that looks up the pairwise distances matrix such as this:
```
def distance(a, b):
    return pairwise_distances[a, b]
```
However you might be happier just by using HDBSCAN with the 'precomputed' distance matrix. The reason that brought me to writing FISHDBC is computing a very large pairwise matrix just doesn't scale.

**Comment by jolespin** [comment]
Yea I'm definitely down to hop on a call in the next week or two!

**Comment by matteodellamico** [comment]
Great! Please let me know at my above email when you can. Thanks!
